name: bet-status-cron
on:
  pull_request:
  schedule:
    - cron: '*/30 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Update Bet Status every 30 minutes
        run: |
          curl --request POST \
          --url '${{ secrets.API_URL }}/bets/status' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
