name: bet-status-cron
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Update Bet Status every 5 minutes
        run: |
          touch .env
          echo API_SECRET_KEY=${{ secrets.API_SECRET_KEY }} >> .env
          echo API_URL=${{ secrets.API_URL }} >> .env
          cat .env
          curl --request POST \
          --url '$API_URL/bets/status' \
          --header 'Authorization: Bearer $API_SECRET_KEY'
