name: schedule-predictions-bet-status-cron
on:
  schedule:
    - cron: '0 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Schedule Predictions & Update Bet Status every 1 hr
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 1
          max_attempts: 3
          retry_on: timeout
          command: |
            curl --request POST \
                  --url '${{ secrets.API_URL }}/predictions/schedulePredictions' \
                  --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'