name: schedule-predictions-cron
on:
  pull_request:
  schedule:
    - cron: '*/10 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Schedule Predictions every 10 minutes
        run: |
          curl --request POST \
          --url `https://blockchain-prediction-game.vercel.app/api/predictions/schedulePredictions` \
          --header `Authorization: Bearer $API_SECRET_KEY`
        env:
          API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}
          API_URL: ${{ secrets.API_URL }}
