name: schedule-predictions-cron
on:
  schedule:
    - cron: '*/10 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Schedule Predictions every 10 minutes
        run: |
          touch .env
          echo API_SECRET_KEY=${{ secrets.API_SECRET_KEY }} >> .env
          echo API_URL=${{ secrets.API_URL }} >> .env
          cat .env
          curl --request POST \
          --url '$API_URL/predictions/schedulePredictions' \
          --header 'Authorization: Bearer $API_SECRET_KEY'
