name: schedule-predictions-cron
on:
  pull_request:
  schedule:
    - cron: '*/10 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Schedule Predictions every 10 minutes
        run: |
          curl --request POST \
          --url '${{ secrets.API_URL }}/predictions/schedulePredictions' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
